const root=document.documentElement;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function read(k){try{return localStorage.getItem(k)||''}catch{return''}}function write(k,v){try{localStorage.setItem(k,v)}catch{}}
function theme(){const saved=read('knowerlife-theme');root.dataset.theme=(saved==='light'||saved==='dark')?saved:(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');const b=$('#themeToggle');const render=()=>{const dark=root.dataset.theme==='dark';b.textContent=dark?'☀':'☾';b.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme')};b.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';write('knowerlife-theme',root.dataset.theme);render()});render()}
function access(){let on=read('knowerlife-accessibility')==='enhanced';const b=$('#accessibilityToggle');const render=()=>{if(on){root.dataset.accessibility='enhanced';root.dataset.fontScale='large'}else{delete root.dataset.accessibility;delete root.dataset.fontScale}b.textContent=on?'A':'A+';b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',on?'Use standard accessibility mode':'Enhanced accessibility')};b.addEventListener('click',()=>{on=!on;write('knowerlife-accessibility',on?'enhanced':'standard');render()});render()}
function mobile(){const d=$('#mobileNav'),b=$('#mobileMenuBtn');b.addEventListener('click',()=>{d.showModal();b.setAttribute('aria-expanded','true')});$('[data-close-nav]').addEventListener('click',()=>d.close());d.addEventListener('close',()=>b.setAttribute('aria-expanded','false'));$$('#mobileNav a').forEach(a=>a.addEventListener('click',()=>d.close()))}
function search(){const input=$('#globalSearch'),cards=$$('.searchable'),status=$('#searchStatus'),filters=$$('#categoryFilters [data-category]');let cat='all';const apply=()=>{const q=input.value.trim().toLowerCase();let n=0;cards.forEach(c=>{const okCat=cat==='all'||c.dataset.category===cat;const hay=(c.dataset.title+' '+c.textContent).toLowerCase();const show=okCat&&(!q||hay.includes(q));c.hidden=!show;if(show)n++});status.textContent=`${n} topic${n===1?'':'s'}`;$('#emptyState').hidden=n>0};input.addEventListener('input',apply);filters.forEach(b=>b.addEventListener('click',()=>{cat=b.dataset.category;filters.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));apply()}));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.focus()}else if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){e.preventDefault();input.focus()}});apply()}
function checker(){const input=$('#requirementInput'),out=$('#requirementResult');$('#requirementCheckBtn').addEventListener('click',()=>{const t=input.value.trim();if(!t){out.textContent='Enter a requirement first.';return}let score=100;const issues=[];for(const word of ['fast','easy','user-friendly','convenient','quickly','etc.'])if(t.toLowerCase().includes(word)){score-=12;issues.push(`Ambiguous word: “${word}”`)}if(!/\d/.test(t)){score-=16;issues.push('Add a measurable threshold where applicable.')}if(!/shall|must|should/i.test(t)){score-=12;issues.push('Make the obligation explicit (shall/must).')}if(t.length<25){score-=12;issues.push('Add enough context to make the behavior testable.')}score=Math.max(0,score);out.textContent=`Quality score: ${score}/100. ${issues.length?issues.join(' '):'Clear, measurable and testable wording.'}`})}
function acceptance(){$('#acceptanceBuildBtn').addEventListener('click',()=>{$('#acceptanceOutput').textContent=`Scenario: acceptance criterion\n\nGiven ${$('#givenInput').value||'…'}\nWhen ${$('#whenInput').value||'…'}\nThen ${$('#thenInput').value||'…'}`})}
function sla(){const calc=()=>{const a=Math.min(100,Math.max(0,Number($('#slaAvailability').value))),days=Math.max(1,Number($('#slaDays').value)),sec=days*86400*(1-a/100),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=Math.round(sec%60);$('#slaOutput').textContent=`${a}% over ${days} days allows ${h?h+' h ':''}${m} min ${s} sec of downtime.`};$('#slaCalcBtn').addEventListener('click',calc);calc()}
function pert(){const calc=()=>{const o=Number($('#pertO').value),m=Number($('#pertM').value),p=Number($('#pertP').value);if([o,m,p].some(Number.isNaN)){return}const e=(o+4*m+p)/6,s=(p-o)/6;$('#pertOutput').textContent=`Expected ≈ ${e.toFixed(2)} · σ ≈ ${s.toFixed(2)} · rough 95% range ≈ ${(e-2*s).toFixed(2)}–${(e+2*s).toFixed(2)}`};$('#pertCalcBtn').addEventListener('click',calc);calc()}
function pwa(){let ev=null,b=$('#installAppBtn');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();ev=e;b.hidden=false});b.addEventListener('click',async()=>{if(!ev)return;ev.prompt();try{await ev.userChoice}catch{}ev=null;b.hidden=true});if('serviceWorker'in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('../../service-worker.js',{scope:'../../'}).catch(()=>{}),{once:true})}
document.addEventListener('DOMContentLoaded',()=>{theme();access();mobile();search();checker();acceptance();sla();pert();pwa()});