const CACHE_VERSION='knowerlife-v11.1.0';
const STATIC_CACHE=`${CACHE_VERSION}-static`,PAGE_CACHE=`${CACHE_VERSION}-pages`,RUNTIME_CACHE=`${CACHE_VERSION}-runtime`;
const scopeUrl=new URL(self.registration.scope);const fromScope=path=>new URL(path,scopeUrl).toString();
const APP_SHELL=['','offline.html','assets/css/styles.css','assets/css/ecosystem-shell.css','assets/js/main.js','assets/js/ecosystem-shell.js','assets/icons/favicon.svg','assets/icons/favicon-96.png','manifest.webmanifest','sa/index.html','sa/styles.css','sa/script.js','creative/index.html','creative/assets/css/styles.css','creative/assets/js/app.js','creative/assets/js/music-core.js','creative/data/tracks.json'].map(fromScope);
self.addEventListener('install',e=>e.waitUntil(caches.open(STATIC_CACHE).then(c=>c.addAll(APP_SHELL))));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>!k.startsWith(CACHE_VERSION)).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
async function networkFirst(req,timeoutMs=3500){const c=await caches.open(PAGE_CACHE),ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeoutMs);try{const r=await fetch(req,{signal:ctl.signal});clearTimeout(timer);if(r.ok)await c.put(req,r.clone());return r}catch{clearTimeout(timer);return(await c.match(req))||(await caches.match(fromScope('offline.html')))}}
async function stale(req){const c=await caches.open(RUNTIME_CACHE),hit=await c.match(req),net=fetch(req).then(r=>{if(r.ok)c.put(req,r.clone());return r}).catch(()=>hit);return hit||net}
async function first(req){const c=await caches.open(STATIC_CACHE),hit=await c.match(req);if(hit)return hit;const r=await fetch(req);if(r.ok)await c.put(req,r.clone());return r}
self.addEventListener('fetch',e=>{const req=e.request,url=new URL(req.url);if(req.method!=='GET'||url.origin!==self.location.origin)return;if(req.headers.has('range')||req.destination==='audio'||/\.(mp3|m4a|ogg|wav)$/i.test(url.pathname))return;if(req.mode==='navigate'){e.respondWith(networkFirst(req));return}if(req.destination==='style'||req.destination==='script'||url.pathname.endsWith('.json')){e.respondWith(stale(req));return}if(req.destination==='image'||req.destination==='font'){e.respondWith(first(req))}});